import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import ReduxProvider from "./providers/ReduxProvider";
import AuthProvider from "./providers/AuthProvider";

export const metadata: Metadata = {
  title: "Order Management System",
  description: "Generated by Insols",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<html lang="en" suppressHydrationWarning>
  <body
    className="antialiased"
    suppressHydrationWarning
  >
            <ReduxProvider>
          <ReactQueryProvider>
            <AuthProvider>
              <Toaster position="top-right" />
              {children}
            </AuthProvider>
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
