export default function HeaderQuotation({ quotation }) {
  return (
    <div className="space-y-6">

      {/* Top Logos Row */}
      <div className="flex justify-between items-center">

{/* LEFT → DEALER LOGO */}
<img
  src={`${process.env.NEXT_PUBLIC_API_URL}/uploads/${quotation?.dealer_id.business_logo}`}
  alt="Dealer Logo"
  className="w-8 h-8 object-contain bg-gray-100 rounded-md p-1"
/>

{/* RIGHT → INDUSTRY LOGO */}
<img
  src={`${process.env.NEXT_PUBLIC_API_URL}/uploads/${quotation?.businessId.business_logo}`}
  alt="Industry Logo"
  className="w-8 h-8 object-contain bg-gray-100 rounded-md p-1"
/>
      </div>

      {/* Bottom Content Row */}
      <div className="flex justify-between items-start gap-6">

        {/* LEFT → DEALER DETAILS */}
        <div>
          <div className="space-y-1">


            {/* <p>
              Address:{" "}
              {order?.dealer_id?.billing_address ||
                order?.dealer_id?.shipping_address ||
                "-"}
            </p> */}
<h3 className="text-lg md:text-xl font-semibold">
  {quotation?.dealer_id?.name || "-"}
</h3>

<p className="text-base md:text-lg font-medium">
  Company: {quotation?.dealer_id?.company_name || "-"}
</p>
            <p>
              City:{" "}
              {quotation?.dealer_id?.city ||
                "-"}
            </p>

            <p>
              Contact:{" "}
              {quotation?.dealer_id?.phone_number ||
                quotation?.dealer_id?.whatsapp_number ||
                "-"}
            </p>
          </div>
        </div>

        {/* RIGHT → ORDER DETAILS */}
        <div className="text-right space-y-1">
          <p className="text-lg md:text-xl font-bold mb-2">Quotation</p>

          <p>Order #: {quotation?.order_number}</p>

          <p>
            Date:{" "}
            {quotation?.quotation_date
              ? new Date(quotation.quotation_date).toLocaleDateString("en-GB")
              : "-"}
          </p>

          <p>
            Expected Delivery:{" "}
            {quotation?.due_date
              ? new Date(quotation.due_date).toLocaleDateString("en-GB")
              : "-"}
          </p>

          <p>
            Generated By: {quotation?.created_by?.name || "-"}
          </p>
        </div>

      </div>
    </div>
  );
}