export default function HeaderQuotation({ quotation }) {
  return (
    <div className="space-y-6">

      {/* 🔝 TOP BAR: LEFT LOGO | CENTER HEADING | RIGHT LOGO */}
      <div className="grid grid-cols-3 items-center">

        {/* LEFT → DEALER LOGO */}
        <div className="flex items-center gap-2">
          <img
            src={quotation?.dealer_id?.business_logo}
            alt="Dealer Logo"
            className="w-12 h-12 object-cover rounded-full border"
          />
        </div>

        {/* CENTER → QUOTATION HEADING */}
        <div className="text-center">
          <h1 className="text-2xl font-bold tracking-wide">
            QUOTATION
          </h1>
        </div>

        {/* RIGHT → COMPANY LOGO */}
        <div className="flex justify-end">
          <img
            src={quotation?.businessId?.business_logo}
            alt="Company Logo"
            className="h-24 object-contain"
          />
        </div>

      </div>

      {/* 🔥 OPTIONAL LINE (PRO LOOK) */}

      {/* 🔽 MAIN SECTION */}
      <div className="flex justify-between items-start mt-4">

        {/* LEFT → DEALER DETAILS */}
        <div className="space-y-1 text-sm">
          <p className="font-semibold">
            {quotation?.dealer_id?.name || "-"}
          </p>
          <p>{quotation?.dealer_id?.company_name || "-"}</p>
          <p>{quotation?.dealer_id?.city || "-"}</p>
          <p>
            {quotation?.dealer_id?.phone_number ||
              quotation?.dealer_id?.whatsapp_number ||
              "-"}
          </p>
        </div>

        {/* RIGHT → QUOTATION DETAILS */}
        <div className="text-right text-sm space-y-1">
          <p>
            <strong>Quotation #:</strong>{" "}
            {quotation?.quotation_number || quotation?.order_number || "-"}
          </p>

          <p>
            <strong>Date:</strong>{" "}
            {quotation?.quotation_date
              ? new Date(quotation.quotation_date).toLocaleDateString("en-GB")
              : "-"}
          </p>

          <p>
            <strong>Valid Until:</strong>{" "}
            {quotation?.valid_until
              ? new Date(quotation.valid_until).toLocaleDateString("en-GB")
              : quotation?.due_date
              ? new Date(quotation.due_date).toLocaleDateString("en-GB")
              : "-"}
          </p>

          <p>
            <strong>Generated By:</strong>{" "}
            {quotation?.created_by?.name || "-"}
          </p>
        </div>

      </div>

    </div>
  );
}