export default function HeaderInvoice({ order }) {
  const formatDate = (date) => {
    if (!date) return "";

    const parsed = new Date(date);

    if (Number.isNaN(parsed.getTime())) return "";
    if (parsed.getFullYear() === 1970) return "";

    return parsed.toLocaleDateString("en-GB");
  };

  const validDueDate = formatDate(order?.due_date);

  return (
    <div className="space-y-6">
      {/* 🔝 TOP BAR: LEFT LOGO | CENTER HEADING | RIGHT LOGO */}
      <div className="grid grid-cols-3 items-center">
        {/* LEFT → DEALER */}
        <div className="flex items-center gap-2">
          {order?.dealer_id?.business_logo && (
            <img
              src={order?.dealer_id?.business_logo}
              alt="Dealer Logo"
              className="w-12 h-12 object-cover rounded-full border"
            />
          )}
        </div>

        {/* CENTER → ORDER HEADING */}
        <div className="text-center">
          <h1 className="text-2xl font-bold tracking-wide">ORDER</h1>
        </div>

        {/* RIGHT → COMPANY */}
        <div className="flex justify-end">
          {order?.businessId?.business_logo && (
            <img
              src={order?.businessId?.business_logo}
              alt="Company Logo"
              className="h-24 object-contain"
            />
          )}
        </div>
      </div>

      {/* 🔽 SECOND ROW → DETAILS */}
      <div className="flex justify-between items-start mt-4 gap-6">
        {/* LEFT → DEALER DETAILS */}
        <div className="text-sm space-y-1 max-w-[55%]">
          <h3 className="font-bold text-gray-900 mb-1">Dealer Details</h3>

          <p>
            <strong>Dealer Name:</strong> {order?.dealer_id?.name || "-"}
          </p>

          <p>
            <strong>Company Name:</strong>{" "}
            {order?.dealer_id?.company_name || "-"}
          </p>

          <p>
            <strong>Phone Number:</strong>{" "}
            {order?.dealer_id?.phone_number || "-"}
          </p>

        </div>

        {/* RIGHT → ORDER DETAILS */}
        <div className="text-right text-sm space-y-1">
          <h3 className="font-bold text-gray-900 mb-1">Order Details</h3>

          <p>
            <strong>Order #:</strong> {order?.order_number || "-"}
          </p>

          <p>
            <strong>Date:</strong> {formatDate(order?.order_date) || "-"}
          </p>

          <p>
            <strong>Expected Delivery:</strong> {validDueDate || "-"}
          </p>

          <p>
            <strong>Generated By:</strong> {order?.created_by?.name || "-"}
          </p>
        </div>
      </div>
    </div>
  );
}