

export default function HeaderInvoice({ order }) {
  const formatDate = (date) => {
  if (!date) return "";

  const parsed = new Date(date);

  if (Number.isNaN(parsed.getTime())) return "";
  if (parsed.getFullYear() === 1970) return "";

  return parsed.toLocaleDateString("en-GB");
};

const validDueDate = formatDate(order?.due_date);
  return (
    <div className="space-y-6">

      {/* 🔝 TOP BAR: LEFT LOGO | CENTER HEADING | RIGHT LOGO */}
      <div className="grid grid-cols-3 items-center">

        {/* LEFT → DEALER */}
        <div className="flex items-center gap-2">
          <img
            src={order?.dealer_id?.business_logo}
            alt="Dealer Logo"
            className="w-12 h-12 object-cover rounded-full border"
          />
        </div>

        {/* CENTER → ORDER HEADING */}
        <div className="text-center">
          <h1 className="text-2xl font-bold tracking-wide">
            ORDER
          </h1>
        </div>

        {/* RIGHT → COMPANY */}
        <div className="flex justify-end">
          <img
            src={order?.businessId?.business_logo}
            alt="Company Logo"
            className="h-24 object-contain"
          />
        </div>

      </div>

      {/* 🔽 SECOND ROW → DETAILS */}
      <div className="flex justify-between items-start mt-4">

        {/* LEFT → DEALER DETAILS */}
        <div className="text-sm space-y-1">
          <p className="font-semibold">{order?.dealer_id?.name}</p>
          <p>{order?.dealer_id?.company_name}</p>
          <p>{order?.dealer_id?.phone_number}</p>
        </div>

        {/* RIGHT → ORDER DETAILS */}
        <div className="text-right text-sm space-y-1">
          <p><strong>Order #:</strong> {order?.order_number}</p>
          <p>
            <strong>Date:</strong>{" "}
            {new Date(order?.order_date).toLocaleDateString("en-GB")}
          </p>
          <p>
  <strong>Expected Delivery:</strong>{" "}
  {validDueDate || ""}
</p>
          <p>
            <strong>Generated By:</strong> {order?.created_by?.name}
          </p>
        </div>

      </div>

    </div>
  );
}