// export default function HeaderInvoice({ order }) {
//   return (
//     <div className="space-y-6">

//       {/* Top Logos Row */}
//       <div className="flex justify-between items-center">

// {/* LEFT → DEALER LOGO */}
// <img
//   src={`${process.env.NEXT_PUBLIC_API_URL}/uploads/${order?.dealer_id.business_logo}`}
//   alt="Dealer Logo"
//   className="w-8 h-8 object-contain bg-gray-100 rounded-md p-1"
// />

// {/* RIGHT → INDUSTRY LOGO */}
// <img
//   src={`${process.env.NEXT_PUBLIC_API_URL}/uploads/${order?.businessId.business_logo}`}
//   alt="Industry Logo"
//   className="w-8 h-8 object-contain bg-gray-100 rounded-md p-1"
// />
//       </div>

//       {/* Bottom Content Row */}
//       <div className="flex justify-between items-start gap-6">

//         {/* LEFT → DEALER DETAILS */}
//         <div>
//           <div className="space-y-1">


//             {/* <p>
//               Address:{" "}
//               {order?.dealer_id?.billing_address ||
//                 order?.dealer_id?.shipping_address ||
//                 "-"}
//             </p> */}
// <h3 className="text-lg md:text-xl font-semibold">
//   {order?.dealer_id?.name || "-"}
// </h3>

// <p className="text-base md:text-lg font-medium">
//   Company: {order?.dealer_id?.company_name || "-"}
// </p>
//             <p>
//               City:{" "}
//               {order?.dealer_id?.city ||
//                 "-"}
//             </p>

//             <p>
//               Contact:{" "}
//               {order?.dealer_id?.phone_number ||
//                 order?.dealer_id?.whatsapp_number ||
//                 "-"}
//             </p>
//           </div>
//         </div>

//         {/* RIGHT → ORDER DETAILS */}
//         <div className="text-right space-y-1">
//           <p className="text-lg md:text-xl font-bold mb-2">Order</p>

//           <p>Order #: {order?.order_number}</p>

//           <p>
//             Date:{" "}
//             {order?.order_date
//               ? new Date(order.order_date).toLocaleDateString("en-GB")
//               : "-"}
//           </p>

//           <p>
//             Expected Delivery:{" "}
//             {order?.due_date
//               ? new Date(order.due_date).toLocaleDateString("en-GB")
//               : "-"}
//           </p>

//           <p>
//             Generated By: {order?.createdBy?.name || "-"}
//           </p>
//         </div>

//       </div>
//     </div>
//   );
// }


export default function HeaderInvoice({ order }) {
  return (
    <div className="space-y-6">

      {/* 🔝 TOP BAR: LEFT LOGO | CENTER HEADING | RIGHT LOGO */}
      <div className="grid grid-cols-3 items-center">

        {/* LEFT → DEALER */}
        <div className="flex items-center gap-2">
          <img
            src={order?.dealer_id?.business_logo}
            alt="Dealer Logo"
            className="w-12 h-12 object-cover rounded-full border"
          />
        </div>

        {/* CENTER → ORDER HEADING */}
        <div className="text-center">
          <h1 className="text-2xl font-bold tracking-wide">
            ORDER
          </h1>
        </div>

        {/* RIGHT → COMPANY */}
        <div className="flex justify-end">
          <img
            src={order?.businessId?.business_logo}
            alt="Company Logo"
            className="h-24 object-contain"
          />
        </div>

      </div>

      {/* 🔽 SECOND ROW → DETAILS */}
      <div className="flex justify-between items-start mt-4">

        {/* LEFT → DEALER DETAILS */}
        <div className="text-sm space-y-1">
          <p className="font-semibold">{order?.dealer_id?.name}</p>
          <p>{order?.dealer_id?.company_name}</p>
          <p>{order?.dealer_id?.phone_number}</p>
        </div>

        {/* RIGHT → ORDER DETAILS */}
        <div className="text-right text-sm space-y-1">
          <p><strong>Order #:</strong> {order?.order_number}</p>
          <p>
            <strong>Date:</strong>{" "}
            {new Date(order?.order_date).toLocaleDateString("en-GB")}
          </p>
          <p>
            <strong>Expected Delivery:</strong>{" "}
            {new Date(order?.due_date).toLocaleDateString("en-GB")}
          </p>
          <p>
            <strong>Generated By:</strong> {order?.createdBy?.name}
          </p>
        </div>

      </div>

    </div>
  );
}